Improve the build-toolchain script.

diff --git a/scripts/build-toolchain b/scripts/build-toolchain
--- a/scripts/build-toolchain
+++ b/scripts/build-toolchain
@@ -1,24 +1,40 @@
-#!/bin/sh -e
+#!/bin/sh
 
 pkglist="make platform=toolchain/\$toolchain list | sort -u"
 version="cut -d: -f1 | cut -d' ' -f2"
 date="date +%X"
+ret=0
 
-function log_begin_msg()
+die()
+{
+	if [ "x$command" = "xclean" ]; then
+		exit $1
+	fi
+
+	if [ "x$1" != "x0" ]; then
+		echo "[`eval $date`] failed"
+		exit $1
+	else
+		echo "[`eval $date`] done"
+	fi
+}
+
+log_begin_msg()
 {
 	echo "$@"
 }
 
-function log_end_msg()
+log_end_msg()
 {
-	if [ "x$?" = "x0" ]; then
-		echo "$@" "done"
+	if [ "x$1" != "x0" ]; then
+		echo "failed ($1)"
+		die $1
 	else
-		echo "$@" "failed ($?)"
+		echo "done"
 	fi
 }
 
-function toolchain_version()
+toolchain_version()
 {
 	toolchain=$1
 	libc=$2
@@ -53,11 +69,12 @@ function toolchain_version()
 }
 
 if [ "x$1" = "x" ]; then
-	echo "usage: $0 toolchain"
+	echo "usage: $0 toolchain [clean]"
 	exit 1
 fi
 
 toolchain="$1"
+command="$2"
 arch=`echo $toolchain | cut -d- -f1`
 cpu=`echo $toolchain | cut -d- -f2`
 os=`echo $toolchain | cut -d- -f3`
@@ -72,36 +89,44 @@ fi
 abi=`echo $libc | sed -e s/uclibc//g -e s/gnu//g`
 libc=`echo $libc | sed -e s/uclibc.*/uclibc/ -e s/gnu.*/gnu/g`
 
-
 if [ ! -d "`pwd`/platform/toolchain/$toolchain" ]; then
 	echo "$toolchain: no such toolchain"
 	exit 1
 fi
 
-echo "[`eval $date`] Building $toolchain toolchain ... "
+if [ "x$command" = "xclean" ]; then
+	log_begin_msg -n "[`eval $date`] Removing $toolchain toolchain ... "
+	make platform=toolchain/$toolchain clean > /dev/null 2>&1
+	ret=$?
+	log_end_msg $ret
+else
+	echo "[`eval $date`] Building $toolchain toolchain ... "
 
-version=`toolchain_version $toolchain $libc`
+	version=`toolchain_version $toolchain $libc`
 
-log_begin_msg -n "[`eval $date`]   Building toolchain ... "
-CROSS_COMPILE="${arch}-${os}-gnu${abi}-" \
-	time make platform=toolchain/$toolchain install > $toolchain.log 2>&1
-log_end_msg
+	log_begin_msg -n "[`eval $date`]   Building toolchain ... "
+	CROSS_COMPILE="${arch}-${os}-gnu${abi}-" \
+		time make platform=toolchain/$toolchain install > $toolchain.log 2>&1
+	ret=$?
+	log_end_msg $ret
 
-if [ ! -f ../toolchains/${toolchain}_${version}.tar.bz2 ]; then
 	log_begin_msg -n "[`eval $date`]   Archiving toolchain ... "
 	tar cjf ../toolchains/${toolchain}_${version}.tar.bz2 \
 		-C platform/toolchain/$toolchain opt
-	log_end_msg
+	ret=$?
+	log_end_msg $ret
+
+	log_begin_msg -n "[`eval $date`]   Cleaning up toolchain ... "
+	make platform=toolchain/$toolchain clean > /dev/null 2>&1
+	ret=$?
+	log_end_msg $ret
+
+	log_begin_msg -n "[`eval $date`]   Installing toolchain ... "
+	tar xjf ../toolchains/${toolchain}_${version}.tar.bz2 \
+		-C platform/toolchain/${toolchain}
+	ret=$?
+	log_end_msg $ret
+
+	die 0
 fi
-
-log_begin_msg -n "[`eval $date`]   Cleaning up toolchain ... "
-make platform=toolchain/$toolchain clean > /dev/null 2>&1
-log_end_msg
-
-log_begin_msg -n "[`eval $date`]   Installing toolchain ... "
-tar xjf ../toolchains/${toolchain}_${version}.tar.bz2 \
-	-C platform/toolchain/${toolchain}
-log_end_msg
-
-echo "[`eval $date`] done"
 
