build system: Add control data to binary packages.
This patch adds basic Debian-like control data to binary packages.
Currently this includes a hook script which can be run right before the
binary package is created and a Debian package control file.

If a file named <package>.binary is found in the package source tree,
the pbs-install script will copy it into the temporariy filesystem from
which the binary package will be generated. The file will also be made
executable.

If a <package>.control file is found in the package source tree, it will
be piped through the opkg-gencontrol script, which will replace the
@TARGET@ and @VERSION@ placeholders with the correct values.

When a binary package is created, the binary script can be used to
perform various actions within the filesystem before it is actually
tarred up. Two parameters are passed to the script: the absolute path to
the temporary filesystem and the version number of the package.

diff --git a/scripts/pbs-install b/scripts/pbs-install
--- a/scripts/pbs-install
+++ b/scripts/pbs-install
@@ -28,6 +28,16 @@ for arg in $@; do
 			shift
 			;;
 
+		-t | --target)
+			prev=target
+			shift
+			;;
+
+		-v | --version)
+			prev=version
+			shift
+			;;
+
 		-s | --source)
 			prev=srcdir
 			shift
@@ -47,6 +57,16 @@ done
 
 if [ "x$prev" != "x" ]; then
 	echo "WARNING: missing argument for parameter: $opt"
+fi
+
+if [ "x$target" = "x" ]; then
+	echo "ERROR: no target configuration specified - try using -t TARGET"
+	exit 1
+fi
+
+if [ "x$version" = "x" ]; then
+	echo "ERROR: no version specified - try using -v VERSION"
+	exit 1
 fi
 
 if [ "x$srcdir" = "x" ]; then
@@ -103,4 +123,19 @@ for package in $packages; do
 			cp -dpR ${srcdir}${src} "${dstdir}/${subdir}${dst}"
 		done
 	)
+
+	debian="${dstdir}/${subdir}/DEBIAN"
+	scripts="${0%/*}"
+
+	mkdir -p "${debian}/hooks"
+
+	if [ -f "${package}.binary" ]; then
+		cp "${package}.binary" "${debian}/hooks/binary"
+		chmod 755 "${debian}/hooks/binary"
+	fi
+
+	if [ -f "${package}.control" ]; then
+		"${scripts}/opkg-gencontrol" -t $target -v $version \
+			"${package}.control" > "${debian}/control"
+	fi
 done
