build: Distinguish between package and pbs version.
To mark packages that have been built from a local source link pbs extends the
version number of the package with a "+"-sign. As binary hook scripts might rely
on the original package version (ie the linux kernel) pass the plain unchanged
package version to the binary hook scripts additionally. The advantage of this
is that no hacks for stripping pbs version suffixes are required, which may
collide with suffixes in the original package version.

Change-Id: Id120d0c4100502b9720a136d0561af2ebabeacc7
Signed-off-by: Julian Scheel <julian@jusst.de>
Reviewed-on: http://review.adnet.avionic-design.de/460
Reviewed-by: Soeren Grunewald <soeren.grunewald@avionic-design.de>

diff --git a/scripts/pbs-binary b/scripts/pbs-binary
--- a/scripts/pbs-binary
+++ b/scripts/pbs-binary
@@ -38,6 +38,11 @@ for arg in $@; do
 			shift
 			;;
 
+		-p | --plain-version)
+			prev=plain_version
+			shift
+			;;
+
 		-b | --binary)
 			prev=binary
 			shift
@@ -64,6 +69,11 @@ if [ "x$version" = "x" ]; then
 	exit 1
 fi
 
+if [ "x$plain_version" = "x" ]; then
+	echo "ERROR: no plain package version specified - try using -v PATH"
+	exit 1
+fi
+
 if [ "x$binary" = "x" ]; then
 	echo "ERROR: no binary directory specified - try using -b PATH"
 	exit 1
@@ -82,7 +92,7 @@ for package in $packages; do
 
 	if [ -x "$srcdir/$package/DEBIAN/hooks/binary" ]; then
 		"$srcdir/$package/DEBIAN/hooks/binary" \
-			"$srcdir/$package" "$version" || exit $?
+			"$srcdir/$package" "$plain_version" || exit $?
 	fi
 
 	log -n "Building binary package: $tarball ... "
