Build system: Rewrite binary packaging system.
Replace the pbs-extract utility with equivalent make script.

Binary packages are now installed and built on a per-binary basis.
Essentially, the .binary target runs the build target of the new
Makefile.binary with a reference to the package's source directory.
A list of all binary packages is then constructed from the list of
.install files, and each binary package is then installed (the files
listed in the corresponding .install file are copied to a binary-
specific destination directory) and built. The .install target runs the
Makefile.binary's extract target, which extracts the binary packages
just built into the platform's sysroot directory.

The new [-q|--quiet] option of the pbs-binary and pbs-install scripts is
used to disable informational output messages from the scripts so that
the build log is cleaner.

diff --git a/scripts/pbs-binary b/scripts/pbs-binary
--- a/scripts/pbs-binary
+++ b/scripts/pbs-binary
@@ -1,7 +1,13 @@
 #!/bin/sh
 
-packages="*.install"
-version="current"
+quiet=no
+
+log()
+{
+	if test "x$quiet" = "xno"; then
+		echo "$@"
+	fi
+}
 
 for arg in $@; do
 	if [ "x$prev" != "x" ]; then
@@ -17,6 +23,11 @@ for arg in $@; do
 	opt=$arg
 
 	case $arg in
+		-q | --quiet)
+			quiet=yes
+			shift
+			;;
+
 		-t | --target)
 			prev=target
 			shift
@@ -43,63 +54,33 @@ if [ "x$prev" != "x" ]; then
 	echo "WARNING: missing argument for parameter: $opt"
 fi
 
-cwd=`pwd`
-base=`dirname $cwd`
-name=`basename $cwd`
-
-while [ "x$name" != "xpackages" ] && [ "x$name" != "xplatforms" ]; do
-	if [ "x$name" = "x$base" ]; then
-		break;
-	fi
-
-	base=`dirname $base`
-	name=`basename $base`
-done
-
-pkg=${cwd#$base/}
-base=`dirname $base`
-
-if [ ! -f "$base/Makefile" ]; then
-	echo "cannot find base directory"
+if [ "x$target" = "x" ]; then
+	echo "ERROR: no target configuration specified - try using -t TARGET"
 	exit 1
 fi
 
-[ "x$binary" = "x" ] && binary="${base}/binary"
-binary="${binary}/${name}/${pkg}"
+if [ "x$version" = "x" ]; then
+	echo "ERROR: no package version specified - try using -v PATH"
+	exit 1
+fi
+
+if [ "x$binary" = "x" ]; then
+	echo "ERROR: no binary directory specified - try using -b PATH"
+	exit 1
+fi
+
+if [ "x$packages" = "x" ]; then
+	echo "ERROR: no package definition specified"
+	exit 1
+fi
+
 srcdir="${binary}/install"
 
 for package in $packages; do
-	package="${package%.install}"
+	package="${package##*/}"
 	tarball="${package}_${version}_${target}.tar.bz2"
-	mkdir -p "${binary}"
 
-	echo -n "Building binary package: $tarball ... "
-
-	cat "$package.install" | (
-		while read line; do
-			[ "x${line#\#}" = "x$line" ] || continue
-
-			src=`echo "$line" | awk '{ print $1 }'`
-			dst=`echo "$line" | awk '{ print $2 }'`
-
-			if [ "x$src" = "x" ]; then
-				continue
-			fi
-
-			if [ "x$dst" = "x" ]; then
-				dst=`dirname "$src"`
-			fi
-
-			if [ "x$dst" = "x/" ]; then
-				dst="$src"
-			fi
-
-			src=${src#/}
-			dst=${dst#/}
-
-			echo "$dst"
-		done
-	) | tar cjpf "$binary/$tarball" -C "$srcdir/$package" -T -
-
-	echo "done"
+	log -n "Building binary package: $tarball ... "
+	tar cjpf "$binary/$tarball" -C "$srcdir/$package" .
+	log "done"
 done
diff --git a/scripts/pbs-install b/scripts/pbs-install
--- a/scripts/pbs-install
+++ b/scripts/pbs-install
@@ -1,6 +1,13 @@
 #!/bin/sh
 
-packages="*.install"
+quiet=no
+
+log()
+{
+	if test "x$quiet" = "xno"; then
+		echo "$@"
+	fi
+}
 
 for arg in $@; do
 	if [ "x$prev" != "x" ]; then
@@ -16,6 +23,11 @@ for arg in $@; do
 	opt=$arg
 
 	case $arg in
+		-q | --quiet)
+			quiet=yes
+			shift
+			;;
+
 		-s | --source)
 			prev=srcdir
 			shift
@@ -42,44 +54,29 @@ if [ "x$srcdir" = "x" ]; then
 	exit 1
 fi
 
-cwd=`pwd`
-base=`dirname $cwd`
-name=`basename $cwd`
-
-while [ "x$name" != "xpackages" ] && [ "x$name" != "xplatforms" ]; do
-	if [ "x$name" = "x$base" ]; then
-		break;
-	fi
-
-	base=`dirname $base`
-	name=`basename $base`
-done
-
-pkg=${cwd#$base/}
-base=`dirname $base`
-
-if [ ! -f "$base/Makefile" ]; then
-	echo "cannot find base directory"
+if [ "x$binary" = "x" ]; then
+	echo "ERROR: no binary directory specified - try using -b PATH"
 	exit 1
 fi
 
-[ "x$binary" = "x" ] && binary="${base}/binary"
-binary="${binary}/${name}/${pkg}"
+if [ "x$packages" = "x" ]; then
+	echo "ERROR: no package definition specified"
+	exit 1
+fi
+
 dstdir="${binary}/install"
-
-echo -n "Removing directory: $dstdir ... "
-rm -rf "$dstdir"
-echo "done"
-
-package_list=`echo $packages`
-if [ "x$package_list" = "x$packages" ]; then
-	echo "ERROR: no package definition found"
-	exit 1
-fi
 
 for package in $packages; do
 	package="${package%.install}"
-	echo "Installing $package "
+	subdir="${package##*/}"
+
+	if [ -d "$dstdir/$subdir" ]; then
+		log -n "Removing directory: $dstdir/$subdir ... "
+		rm -rf "$dstdir/$subdir"
+		log "done"
+	fi
+
+	log "Installing $subdir "
 	cat "$package.install" | (
 		while read line; do
 			[ "x${line#\#}" = "x$line" ] || continue
@@ -93,15 +90,17 @@ for package in $packages; do
 
 			[ "x${src#/}" = "x$src" ] && src="/$src"
 			[ "x${dst#/}" = "x$dst" ] && dst="/$dst"
+
 			# Skip shell paterns expanding to nothing
 			if echo "${srcdir}${src}" | grep -qF -e '*' -e '?' && \
 			   [ "x$(echo ${srcdir}${src})" = "x${srcdir}${src}" ] ; then
 				echo "  skipping empty install patern: ${src}"
 				continue
 			fi
-			echo "  installing: ${src}"
-			mkdir -p "${dstdir}/${package}${dst}"
-			cp -dpR ${srcdir}${src} "${dstdir}/${package}${dst}"
+
+			log "  installing: ${src}"
+			mkdir -p "${dstdir}/${subdir}${dst}"
+			cp -dpR ${srcdir}${src} "${dstdir}/${subdir}${dst}"
 		done
 	)
 done
