net/isc-dhcp: Update to 4.2.0-P1.
This commit actually makes the net/isc-dhcp package compile and work
properly. It has a dependency on the net/bind-libs package, which
provides libraries required by the build process.

diff --git a/packages/net/isc-dhcp/patches/cross-compile.patch b/packages/net/isc-dhcp/patches/cross-compile.patch
--- a/packages/net/isc-dhcp/patches/cross-compile.patch
+++ b/packages/net/isc-dhcp/patches/cross-compile.patch
@@ -1,14 +1,221 @@
+Fix cross-compilation.
+
+From: Thierry Reding <thierry.reding@avionic-design.de>
+
+
+---
+ Makefile.am          |    2 +
+ bind/Makefile        |   75 -------------------------------------------------
+ bind/Makefile.in     |   77 ++++++++++++++++++++++++++++++++++++++++++++++++++
+ client/Makefile.am   |    9 +++---
+ client/scripts/linux |    2 +
+ common/Makefile.am   |    2 +
+ configure.ac         |   11 ++++++-
+ dhcpctl/Makefile.am  |    6 +++-
+ dst/Makefile.am      |    2 +
+ omapip/Makefile.am   |    4 ++-
+ relay/Makefile.am    |    5 +--
+ server/Makefile.am   |    5 +--
+ util/bindvar.sh      |    2 +
+ 13 files changed, 107 insertions(+), 95 deletions(-)
+ delete mode 100644 bind/Makefile
+ create mode 100644 bind/Makefile.in
+
+diff --git a/Makefile.am b/Makefile.am
+index 928d926..14fcd62 100644
+--- a/Makefile.am
++++ b/Makefile.am
+@@ -21,7 +21,7 @@ EXTRA_DIST = RELNOTES LICENSE \
+ 	     util/bindvar.sh \
+ 	     bind/Makefile bind/bind.tar.gz bind/version.tmp 
+ 
+-SUBDIRS = bind includes tests common dst omapip client dhcpctl relay server
++SUBDIRS = $(BIND_SUBDIR) includes tests common dst omapip client dhcpctl relay server
+ 
+ nobase_include_HEADERS = dhcpctl/dhcpctl.h
+ 
+diff --git a/bind/Makefile b/bind/Makefile
+deleted file mode 100644
+index 354dc69..0000000
+--- a/bind/Makefile
++++ /dev/null
+@@ -1,75 +0,0 @@
+-#
+-# Copyright (C) 2009-2010 by Internet Systems Consortium, Inc. ("ISC")
+-#
+-# Permission to use, copy, modify, and/or distribute this software for any
+-# purpose with or without fee is hereby granted, provided that the above
+-# copyright notice and this permission notice appear in all copies.
+-#
+-# THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH
+-# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
+-# AND FITNESS.  IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT,
+-# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
+-# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
+-# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
+-# PERFORMANCE OF THIS SOFTWARE.
+-
+-# $Id: Makefile.bind,v 1.2.2.4 2010/02/17 20:33:56 dhankins Exp $
+-
+-# Configure and build the bind libraries for use by DHCP
+-
+-include ./version.tmp
+-version=${MAJORVER}.${MINORVER}.${PATCHVER}${RELEASETYPE}${RELEASEVER}
+-
+-# bindvar.tmp is constructed by configure, it has the paths for
+-# if GMAKE is blank the shell script couldn't find a gmake to use.
+-# binddir=
+-# GMAKE=
+-include ./bindvar.tmp
+-
+-bindsrcdir=bind-${version}
+-
+-all:
+-# Extract the source from the tarball, if it hasn't been already.
+-	@if test -d ${bindsrcdir} ; then                    \
+-		echo ${bindsrcdir} already unpacked... ;    \
+-	else                                                \
+-		gunzip -c bind.tar.gz | tar xf - ;          \
+-	fi
+-
+-	@if test -z "${GMAKE}"; then                        \
+-		echo "unable to find gmake" 1>&2 ;          \
+-		exit 1;                                     \
+-	fi
+-
+-# Configure the export libraries
+-# Currently disable the epoll and devpoll options as they don't interact
+-# well with the DHCP code.
+-	@echo Configuring BIND Export libraries for DHCP.
+-	@(cd ${bindsrcdir} && ./configure --disable-epoll --disable-devpoll --without-openssl --without-libxml2 --enable-exportlib --enable-threads=no --with-export-includedir=${binddir}/include --with-export-libdir=${binddir}/lib > ${binddir}/configure.log)
+-
+-# Build the export libraries
+-	@echo Building BIND Export libraries - this takes some time.
+-	@(cd ${bindsrcdir}/lib/export ; \
+-	  echo building in `pwd` ; \
+-	  MAKE=${GMAKE} ${GMAKE} > ${binddir}/build.log)
+-
+-	@echo Installing BIND Export libraries to ${binddir}.
+-	@(cd ${bindsrcdir}/lib/export ; \
+-	  MAKE=${GMAKE} ${GMAKE} install > ${binddir}/install.log)
+-
+-clean:
+-	@echo Cleaning BIND export library.
+-	rm -rf ${bindsrcdir} ./lib ./include ./configure.log ./build.log \
+-		./install.log
+-
+-# Include the following so that this Makefile is happy when the parent
+-# tries to use them.
+-
+-distdir:
+-
+-disclean:
+-
+-install:
+-
+-check:
+-
+diff --git a/bind/Makefile.in b/bind/Makefile.in
+new file mode 100644
+index 0000000..d0b04f0
+--- /dev/null
++++ b/bind/Makefile.in
+@@ -0,0 +1,77 @@
++#
++# Copyright (C) 2009-2010 by Internet Systems Consortium, Inc. ("ISC")
++#
++# Permission to use, copy, modify, and/or distribute this software for any
++# purpose with or without fee is hereby granted, provided that the above
++# copyright notice and this permission notice appear in all copies.
++#
++# THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH
++# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
++# AND FITNESS.  IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT,
++# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
++# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
++# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
++# PERFORMANCE OF THIS SOFTWARE.
++
++# $Id: Makefile.bind,v 1.2.2.4 2010/02/17 20:33:56 dhankins Exp $
++
++# Configure and build the bind libraries for use by DHCP
++
++srcdir = @srcdir@
++
++include $(srcdir)/version.tmp
++version=${MAJORVER}.${MINORVER}.${PATCHVER}${RELEASETYPE}${RELEASEVER}
++
++# bindvar.tmp is constructed by configure, it has the paths for
++# if GMAKE is blank the shell script couldn't find a gmake to use.
++# binddir=
++# GMAKE=
++include $(srcdir)/bindvar.tmp
++
++bindsrcdir=bind-${version}
++
++all:
++# Extract the source from the tarball, if it hasn't been already.
++	@if test -d ${bindsrcdir} ; then                     \
++		echo ${bindsrcdir} already unpacked... ;     \
++	else                                                 \
++		gunzip -c $(srcdir)/bind.tar.gz | tar xf - ; \
++	fi
++
++	@if test -z "${GMAKE}"; then                         \
++		echo "unable to find gmake" 1>&2 ;           \
++		exit 1;                                      \
++	fi
++
++# Configure the export libraries
++# Currently disable the epoll and devpoll options as they don't interact
++# well with the DHCP code.
++	@echo Configuring BIND Export libraries for DHCP.
++	@(cd ${bindsrcdir} && ./configure --disable-epoll --disable-devpoll --without-openssl --without-libxml2 --enable-exportlib --enable-threads=no --with-export-includedir=${binddir}/include --with-export-libdir=${binddir}/lib > ${binddir}/configure.log)
++
++# Build the export libraries
++	@echo Building BIND Export libraries - this takes some time.
++	@(cd ${bindsrcdir}/lib/export ; \
++	  echo building in `pwd` ; \
++	  MAKE=${GMAKE} ${GMAKE} > ${binddir}/build.log)
++
++	@echo Installing BIND Export libraries to ${binddir}.
++	@(cd ${bindsrcdir}/lib/export ; \
++	  MAKE=${GMAKE} ${GMAKE} install > ${binddir}/install.log)
++
++clean:
++	@echo Cleaning BIND export library.
++	rm -rf ${bindsrcdir} ./lib ./include ./configure.log ./build.log \
++		./install.log
++
++# Include the following so that this Makefile is happy when the parent
++# tries to use them.
++
++distdir:
++
++disclean:
++
++install:
++
++check:
++
 diff --git a/client/Makefile.am b/client/Makefile.am
-index f01179a..b09f308 100644
+index 77ed055..f8ff52c 100644
 --- a/client/Makefile.am
 +++ b/client/Makefile.am
-@@ -1,3 +1,5 @@
+@@ -1,18 +1,19 @@
 +INCLUDES = -I$(top_srcdir) -I$(top_srcdir)/includes
 +
  dist_sysconf_DATA = dhclient.conf
  sbin_PROGRAMS = dhclient
  dhclient_SOURCES = clparse.c dhclient.c dhc6.c \
-@@ -11,8 +13,8 @@ EXTRA_DIST = $(man_MANS)
+ 		   scripts/bsdos scripts/freebsd scripts/linux scripts/macos \
+ 		   scripts/netbsd scripts/nextstep scripts/openbsd \
+ 		   scripts/solaris scripts/openwrt
+-dhclient_LDADD = ../common/libdhcp.a ../omapip/libomapi.a \
+-		 ../bind/lib/libdns.a ../bind/lib/libisc.a
++dhclient_LDADD = ../common/libdhcp.a ../omapip/libomapi.a @BIND_LIBS@
+ man_MANS = dhclient.8 dhclient-script.8 dhclient.conf.5 dhclient.leases.5
+ EXTRA_DIST = $(man_MANS)
  
  dhclient.o: dhclient.c
  	$(COMPILE) -DCLIENT_PATH='"$(sbindir)"' \
@@ -20,7 +227,7 @@ index f01179a..b09f308 100644
 -		   -DLOCALSTATEDIR='"$(localstatedir)"' -c dhc6.c
 +		   -DLOCALSTATEDIR='"$(localstatedir)"' -c $(srcdir)/dhc6.c
 diff --git a/client/scripts/linux b/client/scripts/linux
-index 49f0977..8b4d7a4 100755
+index 4b3f167..4e1a7f1 100755
 --- a/client/scripts/linux
 +++ b/client/scripts/linux
 @@ -1,4 +1,4 @@
@@ -30,7 +237,7 @@ index 49f0977..8b4d7a4 100755
  # Updated for Linux 2.[12] by Brian J. Murrell, January 1999.
  # No guarantees about this. I'm a novice at the details of Linux
 diff --git a/common/Makefile.am b/common/Makefile.am
-index 8b2f2a9..003c49b 100644
+index a771df3..670e007 100644
 --- a/common/Makefile.am
 +++ b/common/Makefile.am
 @@ -1,4 +1,4 @@
@@ -39,8 +246,50 @@ index 8b2f2a9..003c49b 100644
  
  noinst_LIBRARIES = libdhcp.a
  libdhcp_a_SOURCES = alloc.c bpf.c comapi.c conflex.c ctrace.c discover.c \
+diff --git a/configure.ac b/configure.ac
+index e3cfa46..a065953 100644
+--- a/configure.ac
++++ b/configure.ac
+@@ -483,7 +483,9 @@ AC_CHECK_MEMBER(struct msghdr.msg_control,,
+ #include <sys/socket.h>
+ 	])
+ 
+-libbind=
++libbind_build=yes
++BIND_SUBDIR=bind
++BIND_LIBS="../bind/lib/libdns.a ../bind/lib/libisc.a"
+ AC_ARG_WITH(libbind,
+ 	AC_HELP_STRING([--with-libbind=PATH],
+ 		       [bind includes and libraries are in PATH 
+@@ -498,8 +500,12 @@ no)
+ 	;;
+ *)
+ 	libbind="$use_libbind"
++	BIND_SUBDIR=
++	BIND_LIBS="-L$use_libbind/lib -ldns -lisc"
+ 	;;
+ esac
++AC_SUBST(BIND_SUBDIR)
++AC_SUBST(BIND_LIBS)
+ 
+ # OpenLDAP support.
+ AC_ARG_WITH(ldap,
+@@ -540,6 +546,7 @@ AC_C_FLEXIBLE_ARRAY_MEMBER
+ 
+ AC_OUTPUT([
+   Makefile
++  bind/Makefile
+   client/Makefile
+   common/Makefile
+   common/tests/Makefile
+@@ -552,4 +559,4 @@ AC_OUTPUT([
+   tests/Makefile
+ ])
+ 
+-sh util/bindvar.sh
++sh $srcdir/util/bindvar.sh "$srcdir"
 diff --git a/dhcpctl/Makefile.am b/dhcpctl/Makefile.am
-index 35f1462..dc97eb2 100644
+index 61049be..12e03fe 100644
 --- a/dhcpctl/Makefile.am
 +++ b/dhcpctl/Makefile.am
 @@ -1,3 +1,5 @@
@@ -49,6 +298,20 @@ index 35f1462..dc97eb2 100644
  bin_PROGRAMS = omshell
  lib_LIBRARIES = libdhcpctl.a
  noinst_PROGRAMS = cltest
+@@ -6,10 +8,10 @@ EXTRA_DIST = $(man_MANS)
+ 
+ omshell_SOURCES = omshell.c
+ omshell_LDADD = libdhcpctl.a ../common/libdhcp.a ../omapip/libomapi.a \
+-	        ../bind/lib/libdns.a ../bind/lib/libisc.a
++	        @BIND_LIBS@
+ 
+ libdhcpctl_a_SOURCES = dhcpctl.c callback.c remote.c
+ 
+ cltest_SOURCES = cltest.c
+ cltest_LDADD = libdhcpctl.a ../common/libdhcp.a ../omapip/libomapi.a \
+-	       ../bind/lib/libdns.a ../bind/lib/libisc.a
+\ No newline at end of file
++	       @BIND_LIBS@
 diff --git a/dst/Makefile.am b/dst/Makefile.am
 index 8937fe8..bd235c4 100644
 --- a/dst/Makefile.am
@@ -59,18 +322,8 @@ index 8937fe8..bd235c4 100644
  
  lib_LIBRARIES = libdst.a
  
-diff --git a/minires/Makefile.am b/minires/Makefile.am
-index 6fc1df1..85f0a59 100644
---- a/minires/Makefile.am
-+++ b/minires/Makefile.am
-@@ -1,4 +1,4 @@
--AM_CPPFLAGS = -DMINIRES_LIB -DHMAC_MD5
-+AM_CPPFLAGS = -I$(top_srcdir) -I$(top_srcdir)/includes -DMINIRES_LIB -DHMAC_MD5
- 
- noinst_LIBRARIES = libres.a
- 
 diff --git a/omapip/Makefile.am b/omapip/Makefile.am
-index 6a3c39f..654a638 100644
+index 595950a..91d981e 100644
 --- a/omapip/Makefile.am
 +++ b/omapip/Makefile.am
 @@ -1,3 +1,5 @@
@@ -79,18 +332,31 @@ index 6a3c39f..654a638 100644
  lib_LIBRARIES = libomapi.a
  noinst_PROGRAMS = svtest
  
+@@ -10,5 +12,5 @@ man_MANS = omapi.3
+ EXTRA_DIST = $(man_MANS)
+ 
+ svtest_SOURCES = test.c
+-svtest_LDADD = libomapi.a ../bind/lib/libdns.a ../bind/lib/libisc.a
++svtest_LDADD = libomapi.a @BIND_LIBS@
+ 
 diff --git a/relay/Makefile.am b/relay/Makefile.am
-index ab95e84..4101df1 100644
+index d8757ca..8e52491 100644
 --- a/relay/Makefile.am
 +++ b/relay/Makefile.am
-@@ -1,4 +1,4 @@
+@@ -1,9 +1,8 @@
 -AM_CPPFLAGS = -DLOCALSTATEDIR='"@localstatedir@"'
 +AM_CPPFLAGS = -I$(top_srcdir) -I$(top_srcdir)/includes -DLOCALSTATEDIR='"@localstatedir@"'
  
  sbin_PROGRAMS = dhcrelay
  dhcrelay_SOURCES = dhcrelay.c
+-dhcrelay_LDADD = ../common/libdhcp.a ../omapip/libomapi.a \
+-		 ../bind/lib/libdns.a ../bind/lib/libisc.a
++dhcrelay_LDADD = ../common/libdhcp.a ../omapip/libomapi.a @BIND_LIBS@
+ man_MANS = dhcrelay.8
+ EXTRA_DIST = $(man_MANS)
+ 
 diff --git a/server/Makefile.am b/server/Makefile.am
-index efd3b04..095e511 100644
+index cdfaf47..6061109 100644
 --- a/server/Makefile.am
 +++ b/server/Makefile.am
 @@ -1,4 +1,4 @@
@@ -99,3 +365,26 @@ index efd3b04..095e511 100644
  
  dist_sysconf_DATA = dhcpd.conf
  sbin_PROGRAMS = dhcpd
+@@ -8,8 +8,7 @@ dhcpd_SOURCES = dhcpd.c dhcp.c bootp.c confpars.c db.c class.c failover.c \
+ 
+ dhcpd_CFLAGS = $(LDAP_CFLAGS)
+ dhcpd_LDADD = ../common/libdhcp.a ../omapip/libomapi.a \
+-	      ../dhcpctl/libdhcpctl.a ../bind/lib/libdns.a \
+-	      ../bind/lib/libisc.a
++	      ../dhcpctl/libdhcpctl.a @BIND_LIBS@
+ 
+ man_MANS = dhcpd.8 dhcpd.conf.5 dhcpd.leases.5
+ EXTRA_DIST = $(man_MANS)
+diff --git a/util/bindvar.sh b/util/bindvar.sh
+index 1583a25..051b302 100644
+--- a/util/bindvar.sh
++++ b/util/bindvar.sh
+@@ -29,7 +29,7 @@ for x in gmake gnumake make; do
+ 	fi
+ done
+ 
+-cat <<EOF > bind/bindvar.tmp
++cat <<EOF > "$1/bind/bindvar.tmp"
+ binddir=$binddir/bind
+ GMAKE=$gmake
+ EOF
